export type TickerPhrase = {
  text: string;
  deranged?: boolean;
};

export const TICKER_PHRASES: TickerPhrase[] = [
  { text: "agent is writing code while you spin pixels" },
  { text: "fake coin daemon says maybe" },
  { text: "terminal slots, imaginary receipts" },
  { text: "patch notes from the void" },
  { text: "lint found hope, marked deprecated" },
  { text: "build green, soul pending" },
  { text: "cursor blinks in lowercase dread" },
  { text: "npm install meaning failed" },
  { text: "git blame points at destiny" },
  { text: "deploy button is thinking" },
  { text: "agent split on cosmic whitespace" },
  { text: "slot reel renders undefined" },
  { text: "fake coins jingling in /tmp" },
  { text: "commit message ate the plot" },
  { text: "tests pass in one timeline" },
  { text: "merge conflict with the abyss" },
  { text: "spinner knows your branch name" },
  { text: "paper tokens only, boss" },
  { text: "cache warmed by bad omens" },
  { text: "CLI whispers stable chaos" },
  { text: "autopilot dreams in diffs" },
  { text: "terminal confetti has no value" },
  { text: "agent left a TODO for fate" },
  { text: "prompts aging like temp files" },
  { text: "no cash, just blinking symbols" },
  { text: "shell history remembers everything" },
  { text: "hot reload, cold existence" },
  { text: "reel three returned null" },
  { text: "CI approved the hallucination" },
  { text: "fake jackpot, real stderr" },
  { text: "slops ticker loading entropy" },
  { text: "branch protection for feelings" },
  { text: "your luck is in node_modules" },
  { text: "agent compiling tiny apologies" },
  { text: "grep found nothing but vibes" },
  { text: "sudo make me relevant" },
  { text: "symbols align, meaning refuses" },
  { text: "open tabs nesting in shame" },
  { text: "token meter doing pushups" },
  { text: "preload the absurdity cache" },
  { text: "yarn.lock of the soul" },
  { text: "zero-dollar dopamine packet" },
  { text: "the slot is a div, relax" },
  { text: "git status: emotionally modified" },
  { text: "cron job haunts the lever" },
  { text: "fake coins parked in RAM" },
  { text: "slot daemon patched the omen" },
  { text: "prompts fell through a pipe" },
  { text: "vim quit tutorial still pending" },
  { text: "issue tracker labels the void" },
  { text: "agent writes, user spins" },
  { text: "synthetic luck, local only" },
  { text: "warning: destiny is untyped" },
  { text: "reel checksum looks cursed" },
  { text: "npm audit found a feeling" },
  { text: "output buffering your anxiety" },
  { text: "terminal rain, fake token drain" },
  { text: "backend says maybe later" },
  { text: "stale closure, fresh dread" },
  { text: "grep -R purpose returned 0" },
  { text: "modal open in the afterlife" },
  { text: "compiler saw the reels twitch" },
  { text: "fake balance: spiritually zero" },
  { text: "divination via package manager" },
  { text: "agent culture, reel rupture" },
  { text: "slots in prod, values in jest" },
  { text: "codebase dreaming in ANSI" },
  { text: "ephemeral coins, durable logs" },
  { text: "rebase your expectations" },
  { text: "loading a smaller universe" },
  { text: "terminal slot, cosmic shrug" },
  { text: "LLM wrote the side quest" },
  { text: "grep the void, ship the patch" },
  { text: "no wallet, only widgets" },
  { text: "logs say the symbols are fine" },
  { text: "RNG cosplaying as product" },
  { text: "edge function counting echoes" },
  { text: "slot math is pretend math" },
  { text: "agent queued another miracle" },
  { text: "docs say do not believe" },
  { text: "semver bumps your confusion" },
  { text: "terminal snack for the agent" },
  { text: "fake spin, real stack trace" },
  { text: "null pointer found a home" },
  { text: "hallucinated feature flag on" },
  { text: "build cache wearing a mask" },
  { text: "roll back the moon phase" },
  { text: "JSON ate the prophecy" },
  { text: "coins are props, not promises" },
  { text: "latency tastes like pixels" },
  { text: "agent is spelunking your repo" },
  { text: "feature branch saw the void" },
  { text: "jest snapshots of fake luck" },
  { text: "repl chanting small errors" },
  { text: "PR description left orbit" },
  { text: "TUI shrine to side quests" },
  { text: "chmod +x the nonsense" },
  { text: "bundle size contains feelings" },
  { text: "slot reels need therapy" },
  { text: "warning: vibes uncommitted" },
  { text: "symbols blink in YAML" },
  { text: "fake coins, zero custody" },
  { text: "api route returns maybe" },
  { text: "hooks staring into stdout" },
  { text: "typescript filed a complaint" },
  { text: "ai intern learned ANSI" },
  { text: "your branch has terminal aura" },
  { text: "migrations whisper again" },
  { text: "tiny reels, giant cope" },
  { text: "dev server hums in fake gold" },
  { text: "tty gobbles another thought" },
  { text: "staged files dream of merge" },
  { text: "renderer ate a semicolon" },
  { text: "cursor fed the nonsense" },
  { text: "no house, no cash, just bits" },
  { text: "slots powered by pretend entropy" },
  { text: "agent mumbling over diffs" },
  { text: "ship later, spin fake" },
  { text: "tick, tick, deploy mirage" },
  { text: "shell prompt chewing on fate" },
  { text: "fake coin monk loops stdin", deranged: true },
  { text: "npm audit found forbidden soup", deranged: true },
  { text: "the reels are chewing YAML", deranged: true },
  { text: "chmod 777 on the omen", deranged: true },
  { text: "pretend coin bath, dry keyboard", deranged: true },
  { text: "degen altar made of lint", deranged: true },
  { text: "bash oracle demands fake tokens", deranged: true },
  { text: "stack trace wearing sunglasses", deranged: true },
  { text: "the repo is sweating ANSI", deranged: true },
  { text: "slot sludge passed CI", deranged: true },
  { text: "brainrot compiled with -O0", deranged: true },
  { text: "no cash, only terminal static", deranged: true },
  { text: "agent chews prompt gravel", deranged: true },
  { text: "div spitting counterfeit vibes", deranged: true },
  { text: "slot slime in the render loop", deranged: true },
  { text: "coin icon has basement energy", deranged: true },
  { text: "package-lock seance begins", deranged: true },
  { text: "cursed reel worships stderr", deranged: true },
  { text: "fake jackpot tastes like JSON", deranged: true },
  { text: "degen terminal soup served cold", deranged: true },
  { text: "console.log why are we spinning", deranged: true },
  { text: "agent stapled luck to a div", deranged: true },
  { text: "cache daemon hoards fake coins", deranged: true },
  { text: "runtime licks the slot glass", deranged: true },
  { text: "pixel reels eating drywall", deranged: true },
  { text: "root prompt found the crawlspace", deranged: true },
  { text: "the TUI is legally imaginary", deranged: true },
  { text: "token counter gnaws on stdout", deranged: true },
  { text: "fake coins in emotional debt", deranged: true },
  { text: "spinner unlocked trench mode", deranged: true },
  { text: "agent opened a nonsense socket", deranged: true },
  { text: "this reel has bad permissions", deranged: true },
  { text: "stdout soaked in slot juice", deranged: true },
  { text: "phantom payout, zero custody", deranged: true },
  { text: "prompt sauce on the terminal floor", deranged: true },
  { text: "degen lint ritual at 3am", deranged: true },
  { text: "slot loop wants fake coins", deranged: true },
  { text: "cargo culted the fake jackpot", deranged: true },
  { text: "agent forked the weird branch", deranged: true },
  { text: "no cash, just commandline fumes", deranged: true },
  { text: "claude is wearing the merge button as a hat", deranged: true },
  { text: "cursor promised a small diff and opened a nightclub", deranged: true },
  { text: "slot reels hotpatched my attention span", deranged: true },
  { text: "fake coin sirens in the webpack basement", deranged: true },
  { text: "agent typed rm -rf boredom and missed", deranged: true },
  { text: "context window doing laps around the lever", deranged: true },
  { text: "vibe debt refinanced at terminal rates", deranged: true },
  { text: "patch fever redacted by compliance", deranged: true },
  { text: "spin button found a second spin button", deranged: true },
  { text: "the diff is green but the room is magenta", deranged: true },
  { text: "synthetic dopamine leaking into stderr", deranged: true },
  { text: "agent wrote a casino in your wait state", deranged: true },
  { text: "spacebar has entered its villain arc", deranged: true },
  { text: "tokens are screaming in lowercase neon", deranged: true },
  { text: "the slot machine is pair programming badly", deranged: true },
  { text: "npm install opened a velvet rope", deranged: true },
  { text: "fake jackpot doing donuts in tmp", deranged: true },
  { text: "agent promised tests then summoned confetti", deranged: true },
  { text: "diff hunks bathing in counterfeit gold", deranged: true },
  { text: "reel three has main character latency", deranged: true },
  { text: "leaderboard thirst trapped the terminal", deranged: true },
  { text: "server-side rng found the loudest shirt", deranged: true },
  { text: "hallucination payout arrived wearing sunglasses", deranged: true },
  { text: "slot room smells like hot reload", deranged: true },
  { text: "agent is sanding the repo with a prompt", deranged: true },
  { text: "fake coins bouncing off the linter", deranged: true },
  { text: "ship it button filed for emotional damages", deranged: true },
  { text: "terminal casino found a new bad idea", deranged: true },
  { text: "the reels unionized against focus", deranged: true },
  { text: "context limit turned into a strobe light", deranged: true },
  { text: "ai intern eating stack traces for breakfast", deranged: true },
  { text: "slots are not a coping strategy, allegedly", deranged: true },
  { text: "the prompt got into the ceiling wires", deranged: true },
  { text: "fake coin weather advisory in effect", deranged: true },
  { text: "agent status: rewriting the vibes layer", deranged: true },
  { text: "payout table wearing too much cologne", deranged: true },
  { text: "spacebar liquidity desk is open", deranged: true },
  { text: "terminal attention economy hit max volume", deranged: true },
  { text: "rebase casino entered the glass cube", deranged: true },
  { text: "zero cash value, maximum screen damage", deranged: true },
];
